Script started on Thu 13 Nov 2014 06:44:20 PM PST
]0;jinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13: ~/Desktop/rshell/testsjinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13:~/Desktop/rshell/tests$ cd ..
]0;jinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13: ~/Desktop/rshelljinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13:~/Desktop/rshell$ ls
[0m[01;34mbin[0m  LICENSE  Makefile  README.md  [01;34msrc[0m  [01;34mtests[0m
]0;jinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13: ~/Desktop/rshelljinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13:~/Desktop/rshell$ make clean
rm -rf ./bin
]0;jinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13: ~/Desktop/rshelljinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13:~/Desktop/rshell$ make [K
mkdir bin
g++ -Wall -Werror -ansi -pedantic ./src/rshell.cpp -o ./bin/rshell 
g++ -Wall -Werror -ansi -pedantic ./src/ls.cpp -o ./bin/ls 
]0;jinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13: ~/Desktop/rshelljinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13:~/Desktop/rshell$ bin/ls ls
bin            Makefile       src            LICENSE        README.md      
tests          
]0;jinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13: ~/Desktop/rshelljinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13:~/Desktop/rshell$ bin/ls ls -l
drwxrwxr-x  2 ]0;jinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13: ~/Desktop/rshelljinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13:~/Desktop/rshell$ bin/ls ls -l[K[5Pmake clean[Kbin/ls ls
bin            Makefile       src            LICENSE        README.md      
tests          
]0;jinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13: ~/Desktop/rshelljinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13:~/Desktop/rshell$ bin/ls ls -l[K[K^C
]0;jinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13: ~/Desktop/rshelljinsongwei@jinsongwei-Lenovo-IdeaPad-Yoga-13:~/Desktop/rshell$ exit
exit

Script done on Thu 13 Nov 2014 06:46:28 PM PST
